fix: Fix workflow trigger tag pattern 3 (#7)

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -2,11 +2,24 @@ name: publish
 
 on:
   push:
-    tags:
-      - '*'
+    tags: ['core@[0-9].[0-9]+.[0-9]+', 'solvers@[0-9].[0-9]+.[0-9]+', 'core@[0-9].[0-9]+.[0-9]+-rc', 'solvers@[0-9].[0-9]+.[0-9]+-rc']
+    branches: ['main']
 
 jobs:
+  validate-tag:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check tag format
+        run: |
+          TAG_NAME=${{ github.ref_name }}
+          if [[ ! "$TAG_NAME" =~ ^(core|solvers)@[0-9]+\.[0-9]+\.[0-9]+(-rc)?$ ]]; then
+            echo "Invalid tag format. Tag must follow 'packageName@X.Y.Z' or 'packageName@X.Y.Z-rc' format."
+            exit 1  # Fail the workflow if the tag format is invalid
+          fi
+          echo "Valid tag format: $TAG_NAME"
+
   build:
+    needs: validate-tag
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
@@ -15,9 +28,7 @@ jobs:
       - uses: actions/setup-python@v5
         with:
           python-version: "3.12"
-      - run: |
-          echo "PACKAGE_NAME=$(echo ${{ github.ref_name }} | cut -d'@' -f1)" >> $GITHUB_ENV
-          echo "STAGE=${{ endsWith(github.ref_name, 'rc') && 'preview' || 'live' }}" >> $$GITHUB_ENV
+      - run: echo "PACKAGE_NAME=$(echo ${{ github.ref_name }} | cut -d'@' -f1)" >> $GITHUB_ENV
       - run: |
           pipx install poetry
           cd ${{ env.PACKAGE_NAME }}
@@ -39,6 +50,8 @@ jobs:
         with:
           name: 'distribution'
           path: dist/
+      - run: echo "STAGE=${{ endsWith(github.ref_name, 'rc') && 'preview' || 'live' }}" >> $GITHUB_ENV
+      - run: echo ${{ env.STAGE }}
       - uses: pypa/gh-action-pypi-publish@release/v1
         with:
           repository-url: ${{ env.STAGE == 'preview' && 'https://test.pypi.org/legacy/' || 'https://pypi.org/simple/' }}
